# Generated by Django 4.1.2 on 2022-11-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_message_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="sender",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
